# docker-compose.yml

version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ass
      POSTGRES_DB: ecommerce
    ports: 
      - '54320:5432'
    volumes:
      - e-commerce-admin-db:/var/lib/postgresql/data

  e-commerce-admin:
    build:
      context: .
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - '3030:3030'

volumes:
  e-commerce-admin-db: